"""container, page and place added

Revision ID: 32dea3e368cc
Revises: 3b7a2d0b5455
Create Date: 2015-07-12 21:09:59.829298

"""

# revision identifiers, used by Alembic.
revision = '32dea3e368cc'
down_revision = '3b7a2d0b5455'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('''ALTER TABLE photo DROP PRIMARY KEY ''')
    op.execute('''
      ALTER TABLE photo ADD COLUMN id
      INT auto_increment PRIMARY KEY FIRST;''')
    # drop forgein key constraint on photo to photoproject
    op.execute('''ALTER TABLE photo DROP FORGEIN KEY 'photo_ibfk_1' ''')
    op.execute('''ALTER TABLE photo DROP FORGEIN KEY 'photo_ibfk_2 ' ''')
    op.execute('''ALTER TABLE photo ADD COLUMN pproject_id INT''')
    # add new column photoproject_id to photo

    # update it with ids from photoproject

    #ALTER TABLE users ADD CONSTRAINT fk_grade_id FOREIGN KEY (grade_id) REFERENCES grades(id);
    # add new foregein key constraint on photo to photoproject
    #op.execute('''ALTER TABLE photo ADD CONSTRAINT photo_ibfk_3 FORGEIN_KEY ''')
        
    op.execute('''ALTER TABLE photoproject DROP PRIMARY KEY ''')
    op.execute('''
      ALTER TABLE photoproject ADD COLUMN id
      INT auto_increment PRIMARY KEY FIRST;''')
    op.execute('''UPDATE photo INNER JOIN photoproject ON photo.projectkey = photoproject.projectkey SET photo.pproject_id = photoproject.id''')

    # add foreign key to photo

    op.execute('''ALTER TABLE user DROP PRIMARY KEY ''')
    op.execute('''
      ALTER TABLE user ADD COLUMN id
      INT auto_increment PRIMARY KEY FIRST;''')

    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pagenum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinate_x', sa.Integer(), nullable=True),
    sa.Column('coordinate_y', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_num', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.drop_column(u'user', u'userid')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.drop_column(u'user', 'id')
    op.drop_column(u'photoproject', 'id')
    op.drop_column(u'photo', 'id')
    op.drop_table('container')
    op.drop_table('position')
    op.drop_table('page')

    op.add_column(u'user', sa.Column(u'userid', mysql.INTEGER(display_width=11), nullable=False))


    op.execute('''ALTER TABLE user ADD PRIMARY KEY (username)''')
    op.execute('''ALTER TABLE photo ADD PRIMARY KEY (photokey)''')
    op.execute('''ALTER TABLE photoproject   ADD PRIMARY KEY (projectkey)''')

### end Alembic commands ###
