"""container, page and place added

Revision ID: 32dea3e368cc
Revises: 3b7a2d0b5455
Create Date: 2015-07-12 21:09:59.829298

"""

# revision identifiers, used by Alembic.
revision = '32dea3e368cc'
down_revision = '3b7a2d0b5455'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'photo', sa.Column('id', sa.Integer(), nullable=False,
                                      index=True, autoincrement=True))
    op.add_column(u'photoproject', sa.Column('id', sa.Integer(), nullable=False,
                                             index=True, autoincrement=True))
    op.add_column(u'user', sa.Column('id', sa.Integer(), nullable=False,
                                     index=True, autoincrement=True))
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pagenum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinate_x', sa.Integer(), nullable=True),
    sa.Column('coordinate_y', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_num', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.drop_column(u'user', u'userid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('container')
    op.drop_table('position')
    op.drop_table('page')
    op.drop_column(u'user', 'id')
    op.add_column(u'user', sa.Column(u'userid', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column(u'photoproject', 'id')
    op.drop_column(u'photo', 'id')

    ### end Alembic commands ###
