"""sec

Revision ID: 3b7a2d0b5455
Revises: ed5324090fa
Create Date: 2015-07-06 00:22:32.144327

"""

# revision identifiers, used by Alembic.
revision = '3b7a2d0b5455'
down_revision = 'ed5324090fa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photo', 'name',
               existing_type=mysql.VARCHAR(length=35),
               nullable=False)
    op.alter_column('photo', 'photourl',
               existing_type=mysql.VARCHAR(length=155),
               nullable=False)
    op.alter_column('photo', 'placenumber',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('photo', 'projectkey',
               existing_type=mysql.VARCHAR(length=35),
               nullable=False)
    op.alter_column('photoproject', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('photoproject', 'name',
               existing_type=mysql.VARCHAR(length=35),
               nullable=False)
    op.alter_column('photoproject', 'placenumber',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('photoproject', 'published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=35),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=35),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('photoproject', 'published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('photoproject', 'placenumber',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('photoproject', 'name',
               existing_type=mysql.VARCHAR(length=35),
               nullable=True)
    op.alter_column('photoproject', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('photo', 'projectkey',
               existing_type=mysql.VARCHAR(length=35),
               nullable=True)
    op.alter_column('photo', 'placenumber',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('photo', 'photourl',
               existing_type=mysql.VARCHAR(length=155),
               nullable=True)
    op.alter_column('photo', 'name',
               existing_type=mysql.VARCHAR(length=35),
               nullable=True)
    ### end Alembic commands ###
