"""first

Revision ID: ed5324090fa
Revises: 
Create Date: 2015-07-03 22:00:52.621945

"""

# revision identifiers, used by Alembic.
revision = 'ed5324090fa'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=35), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('userid', 'username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('photoproject',
    sa.Column('projectkey', sa.String(length=35), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=True),
    sa.Column('description', sa.String(length=35), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('placenumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('projectkey')
    )
    op.create_table('photo',
    sa.Column('photokey', sa.String(length=35), nullable=False),
    sa.Column('projectkey', sa.String(length=55), nullable=True),
    sa.Column('name', sa.String(length=35), nullable=True),
    sa.Column('placenumber', sa.Integer(), nullable=True),
    sa.Column('photourl', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['projectkey'], ['photoproject.projectkey'], ),
    sa.PrimaryKeyConstraint('photokey')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('photoproject')
    op.drop_table('user')
    ### end Alembic commands ###
